version: '3.8'

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./hass-config:/config
      - ./hass-recordings:/recordings
      - /etc/localtime:/etc/localtime:ro
      - /Users/homeassistant/langchain-ha-bridge/langchain_remote:/config/custom_components/langchain_remote
    environment:
      - TZ=Australia/Sydney
    ports:
      - '8123:8123'
    restart: unless-stopped

  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper:latest
    command: --model tiny-int8 --language en
    volumes:
      - ./whisper-data:/data
    environment:
      - TZ=Australia/Sydney
    ports:
      - '10300:10300'
    restart: unless-stopped

  piper:
    container_name: piper
    image: rhasspy/wyoming-piper:latest
    command: --voice en_US-lessac-medium
    volumes:
      - ./piper-data:/data
    environment:
      - TZ=Australia/Sydney
    ports:
      - '10200:10200'
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434       # same effect as --host/--port
    ports:
      - "11434:11434"
    entrypoint: [ "ollama", "serve"]
    volumes:
      - ./ollama-data:/root/.ollama
    restart: unless-stopped
    healthcheck: # wait for API to come up
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 30s
      retries: 5
