version: '3.8'

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./data/hass-config:/config
      - ./data/hass-recordings:/recordings
      - /etc/localtime:/etc/localtime:ro
      - ../../custom_components/langchain_conversation:/config/custom_components/langchain_conversation
    environment:
      - TZ=Australia/Sydney
    ports:
      - '8123:8123'
    restart: unless-stopped
